# Generated by Django 4.0.5 on 2022-06-26 19:37

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=phone_field.models.PhoneField(default='0962684457', max_length=31, unique=True),
            preserve_default=False,
        ),
    ]
