# Generated by Django 4.0.5 on 2022-06-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_alter_customuser_password_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
