# Generated by Django 4.0.5 on 2022-07-02 11:32

import accounting.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_alter_specialization_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=16, unique=True, validators=[accounting.validators.validate_phone_number]),
        ),
    ]
