# Generated by Django 4.0.5 on 2022-07-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.IntegerField(choices=[(0, 'Visitor'), (1, 'Admin'), (2, 'Worker')], default=0),
        ),
    ]
